import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ta' | 'ml' | 'ne' | 'te' | 'kn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LANGUAGE_OPTIONS: { code: Language; label: string; nativeLabel: string }[] = [
  { code: 'en', label: 'English', nativeLabel: 'English' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்' },
  { code: 'ml', label: 'Malayalam', nativeLabel: 'മലയാളം' },
  { code: 'ne', label: 'Nepali', nativeLabel: 'नेपाली' },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు' },
  { code: 'kn', label: 'Kannada', nativeLabel: 'ಕನ್ನಡ' },
];

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    back: "Back", close: "Close", confirm: "Confirm", save: "Save", cancel: "Cancel",
    edit: "Edit", delete: "Delete", loading: "Loading...", error: "Error", success: "Success",
    logout: "Logout", login: "Login", submit: "Submit",

    // Auth
    signIn: "Sign In", createAccount: "Create Account", welcomeBack: "Welcome back",
    joinHarvestLog: "Join Harvest-Log", enterCredentials: "Enter your credentials to access your account",
    createAccountDesc: "Create an account to start trading produce",
    fullName: "Full Name", enterYourName: "Enter your name", phoneNumber: "Phone Number",
    email: "Email", password: "Password", enterPassword: "Enter your password",
    iWantTo: "I want to", buyer: "Buyer", seller: "Seller", transporter: "Transporter",
    purchaseProduce: "Purchase fresh produce", sellYourHarvest: "Sell your harvest",
    deliverAndEarn: "Deliver and earn", orTryDemo: "Or try demo",
    connectingFarms: "Connecting Farms", toMarkets: "to Markets,", intelligently: "Intelligently.",
    platformDesc: "Real-time logistics, AI-powered market intelligence, and agricultural credit assessment — all in one platform.",
    realTimeGps: "Real-time GPS", smartRoutes: "Smart Routes", riskEngine: "Risk Engine", liveChat: "Live Chat",
    agriFintech: "Agri-FinTech Platform",

    // Landing
    startTrading: "Start Trading", watchDemo: "Watch Demo",
    agriFinTechLogistics: "Agri-FinTech + Real-Time Logistics",
    heroTitle: "Connecting Farms to Markets,",
    heroSubtitle: "Real-time GPS tracking, AI-powered market intelligence, and agricultural credit assessment — all in one zero-cost platform for farmers, buyers, and transporters.",
    poweredByInnovation: "Powered by Innovation",
    poweredDesc: "Everything you need to revolutionize agricultural logistics and finance.",
    onePlatformThreeRoles: "One Platform, Three Roles",
    rolesDesc: "Whether you're buying, selling, or delivering — we've got you covered.",
    readyToTransform: "Ready to Transform Agriculture?",
    ctaDesc: "Join thousands of farmers, buyers, and transporters already using Harvest-Log.",
    getStartedFree: "Get Started Free",
    activeFarmers: "Active Farmers", tradeVolume: "Trade Volume",
    deliveryRate: "Delivery Rate", userRating: "User Rating",
    farmersAndSellers: "Farmers & Sellers", buyers: "Buyers", transporters: "Transporters",

    // Navigation
    marketplace: "Marketplace", orderAndTrack: "Order & Track", uglyProduce: "On-Demand Picks",
    myOrders: "My Orders", dashboard: "Dashboard", inventory: "Inventory",
    orders: "Orders", analytics: "Analytics", activeRide: "Active Ride", earnings: "Earnings",

    // Dashboard
    welcomeBackDash: "Welcome back! 👋", trackOrdersDiscover: "Track your orders and discover fresh produce",
    browseMarket: "Browse Market", findFreshProduce: "Find fresh produce",
    liveDeliveryTracking: "Live delivery tracking", saveFood: "Save Food",
    uglyProduceDeals: "Ugly produce deals", trackDeliveries: "Track deliveries",
    recentOrders: "Recent Orders", viewAll: "View All",
    sellerDashboard: "Seller Dashboard 🌾", manageInventoryTrack: "Manage your inventory and track orders",
    totalProducts: "Total Products", activeOrders: "Active Orders",
    revenueMtd: "Revenue (MTD)", avgRating: "Avg Rating",
    manageInventory: "Manage Inventory", addEditRemove: "Add, edit, or remove products",
    pendingOrders: "Pending Orders", ordersAwaitingAction: "orders awaiting action",
    recentActivity: "Recent Activity",
    transporterDashboard: "Transporter Dashboard 🚚",
    acceptDeliveriesMaximize: "Accept deliveries and maximize your earnings",
    totalDeliveries: "Total Deliveries", distanceKm: "Distance (km)",
    earningsMtd: "Earnings (MTD)", nearbyRequests: "Nearby Requests",
    noNearbyRequests: "No nearby requests right now",
    estEarnings: "Est. earnings", reject: "Reject", accept: "Accept",

    // Marketplace
    browseFreshProduce: "Browse fresh produce from local farmers",
    searchProductsSellers: "Search products or sellers...", all: "All",
    yourCart: "Your Cart", subtotal: "Subtotal", deliveryFee: "Delivery Fee",
    total: "Total", proceedToCheckout: "Proceed to Checkout", items: "items",

    // Live Tracking
    orderAndTracking: "Order & Tracking",
    placeOrdersTrackChat: "Place orders, track deliveries, and chat — all in one place",
    locating: "Locating…", live: "Live", ready: "Ready",
    entities: "Entities", routes: "Routes",
    calculatingRoutes: "Calculating routes…",
    placeDemoOrder: "Place Demo Order",
    advanceStatus: "Advance Status", stopDemo: "Stop Demo",
    orderPlaced: "Order Placed", orderPickedUp: "Order Picked Up",
    inTransit: "In Transit", delivered: "Delivered", completed: "Completed",

    // Ugly Produce / On-Demand Picks
    saveImperfectProduce: "Save Imperfect Produce 🥕",
    swipeRightToSave: "Swipe right to save food, save money, and save the planet",
    ofProduceWasted: "of produce wasted", priceSavings: "price savings",
    equallyNutritious: "equally nutritious",
    youreAHero: "You're a Hero!",
    youLikedItems: "imperfect produce items",
    addItemsToCart: "Add items to cart",

    // Seller Inventory
    addProduct: "Add Product", searchProducts: "Search products…",
    productName: "Product Name", category: "Category",
    pricePerKg: "Price (₹/kg)", availableKg: "Available (kg)",
    freshnessDays: "Freshness (days)", organic: "Organic",
    uglyProduceToggle: "Ugly Produce", saveChanges: "Save Changes",
    noProductsFound: "No products found", editProduct: "Edit Product",

    // Seller Orders
    sellerOrders: "Seller Orders",
    trackManageBuyerOrders: "Track and manage buyer orders in real time",
    noOrdersYet: "No orders yet",
    itemsLabel: "Items", totalLabel: "Total", delivery: "Delivery",
    transporterLabel: "Transporter", placed: "Placed",

    // Transporter Earnings
    earningsTitle: "Earnings",
    trackDeliveryIncome: "Track your delivery income and trip history",
    thisWeek: "This Week", totalTrips: "Total Trips", totalDistance: "Total Distance",
    recentTripHistory: "Recent Trip History", trips: "trips",

    // Risk Engine
    monteCarloRiskEngine: "Monte Carlo Risk Engine 📊",
    riskEngineDesc: "AI-powered agricultural credit assessment using 10,000 weather simulations",
    assessmentParameters: "Assessment Parameters",
    cropType: "Crop Type", region: "Region", landArea: "Land Area (hectares)",
    investmentAmount: "Investment Amount (₹)",
    runRiskAssessment: "Run Risk Assessment", running: "Running",
    riskAssessment: "Risk Assessment", confidence: "Confidence",
    basedOnSimulations: "Based on simulations",
    expectedYield: "Expected Yield", tonnesHectare: "tonnes/hectare",
    stdDeviation: "std deviation", weatherAssumptions: "Weather Assumptions",
    rainfall: "Rainfall", temperature: "Temperature", humidity: "Humidity",
    recommendation: "Recommendation",
    noAssessmentYet: "No Assessment Yet",
    configureParams: "Configure the parameters and run the Monte Carlo simulation to get a risk assessment.",
    aboutMonteCarlo: "About Monte Carlo Simulation",
    monteCarloInfo: "This engine runs 10,000 simulations using historical weather data to predict crop yield outcomes.",

    // Language
    selectLanguage: "Select Language", languageChanged: "Language changed!",
    english: "English", tamil: "தமிழ்", malayalam: "മലയാളം",
    nepali: "नेपाली", telugu: "తెలుగు", kannada: "ಕನ್ನಡ",
  },

  ta: {
    back: "பின்", close: "மூடு", confirm: "உறுதிப்படுத்து", save: "சேமி", cancel: "ரத்து",
    edit: "திருத்து", delete: "நீக்கு", loading: "ஏற்றுகிறது...", error: "பிழை", success: "வெற்றி",
    logout: "வெளியேறு", login: "உள்நுழை", submit: "சமர்ப்பி",
    signIn: "உள்நுழை", createAccount: "கணக்கை உருவாக்கு", welcomeBack: "மீண்டும் வரவேற்கிறோம்",
    joinHarvestLog: "Harvest-Log இல் சேரவும்",
    enterCredentials: "உங்கள் கணக்கை அணுக சான்றுகளை உள்ளிடவும்",
    createAccountDesc: "வர்த்தகம் தொடங்க கணக்கை உருவாக்கவும்",
    fullName: "முழு பெயர்", enterYourName: "உங்கள் பெயரை உள்ளிடவும்",
    phoneNumber: "தொலைபேசி எண்", email: "மின்னஞ்சல்", password: "கடவுச்சொல்",
    enterPassword: "கடவுச்சொல்லை உள்ளிடவும்",
    iWantTo: "நான் விரும்புகிறேன்", buyer: "வாங்குபவர்", seller: "விற்பனையாளர்",
    transporter: "போக்குவரத்து", purchaseProduce: "புதிய விளைபொருட்கள் வாங்கவும்",
    sellYourHarvest: "உங்கள் அறுவடையை விற்கவும்", deliverAndEarn: "டெலிவரி செய்து சம்பாதிக்கவும்",
    orTryDemo: "அல்லது டெமோ",
    connectingFarms: "பண்ணைகளை இணைக்கிறது", toMarkets: "சந்தைகளுக்கு,",
    intelligently: "புத்திசாலித்தனமாக.",
    platformDesc: "நிகழ்நேர தளவாடம், AI சந்தை புத்திசாலித்தனம் மற்றும் விவசாய கடன் மதிப்பீடு.",
    realTimeGps: "நிகழ்நேர GPS", smartRoutes: "ஸ்மார்ட் வழிகள்",
    riskEngine: "ரிஸ்க் இயந்திரம்", liveChat: "நேரடி அரட்டை",
    agriFintech: "விவசாய-FinTech தளம்",
    startTrading: "வர்த்தகத்தைத் தொடங்கு", watchDemo: "டெமோ பார்",
    marketplace: "சந்தை", orderAndTrack: "ஆர்டர் & டிராக்",
    uglyProduce: "ஆன்-டிமாண்ட் பிக்ஸ்", myOrders: "என் ஆர்டர்கள்",
    dashboard: "டாஷ்போர்டு", inventory: "சரக்கு", orders: "ஆர்டர்கள்",
    analytics: "பகுப்பாய்வு", activeRide: "செயலில் சவாரி", earnings: "வருமானம்",
    welcomeBackDash: "மீண்டும் வரவேற்கிறோம்! 👋",
    trackOrdersDiscover: "உங்கள் ஆர்டர்களைக் கண்காணித்து புதிய விளைபொருட்களைக் கண்டறியவும்",
    browseMarket: "சந்தையை உலாவவும்", findFreshProduce: "புதிய விளைபொருட்களைக் கண்டறியவும்",
    liveDeliveryTracking: "நேரடி டெலிவரி கண்காணிப்பு",
    saveFood: "உணவைக் காப்பாற்று", uglyProduceDeals: "சிறப்பு சலுகைகள்",
    trackDeliveries: "டெலிவரிகளைக் கண்காணி",
    recentOrders: "சமீபத்திய ஆர்டர்கள்", viewAll: "அனைத்தும் காண்",
    sellerDashboard: "விற்பனையாளர் டாஷ்போர்டு 🌾",
    manageInventoryTrack: "உங்கள் சரக்கு நிர்வகித்து ஆர்டர்களைக் கண்காணிக்கவும்",
    totalProducts: "மொத்த பொருட்கள்", activeOrders: "செயலில் ஆர்டர்கள்",
    revenueMtd: "வருவாய் (MTD)", avgRating: "சராசரி மதிப்பீடு",
    manageInventory: "சரக்கு நிர்வகி", addEditRemove: "பொருட்களைச் சேர்க்க, திருத்த அல்லது நீக்க",
    pendingOrders: "நிலுவையில் ஆர்டர்கள்", ordersAwaitingAction: "செயல் காத்திருக்கும் ஆர்டர்கள்",
    recentActivity: "சமீபத்திய செயல்பாடு",
    transporterDashboard: "போக்குவரத்து டாஷ்போர்டு 🚚",
    acceptDeliveriesMaximize: "டெலிவரிகளை ஏற்று உங்கள் வருமானத்தை அதிகரிக்கவும்",
    totalDeliveries: "மொத்த டெலிவரிகள்", distanceKm: "தூரம் (km)",
    earningsMtd: "வருமானம் (MTD)", nearbyRequests: "அருகிலுள்ள கோரிக்கைகள்",
    noNearbyRequests: "தற்போது அருகிலுள்ள கோரிக்கைகள் இல்லை",
    estEarnings: "மதிப்பிட்ட வருமானம்", reject: "நிராகரி", accept: "ஏற்கவும்",
    browseFreshProduce: "உள்ளூர் விவசாயிகளிடமிருந்து புதிய விளைபொருட்கள்",
    searchProductsSellers: "பொருட்கள் அல்லது விற்பனையாளர்களைத் தேடு...", all: "அனைத்தும்",
    yourCart: "உங்கள் கூடை", subtotal: "மொத்தம்", deliveryFee: "டெலிவரி கட்டணம்",
    total: "மொத்தம்", proceedToCheckout: "செக்அவுட்டிற்குச் செல்", items: "பொருட்கள்",
    orderAndTracking: "ஆர்டர் & கண்காணிப்பு",
    placeOrdersTrackChat: "ஆர்டர் செய்யுங்கள், டெலிவரிகளைக் கண்காணியுங்கள்",
    locating: "கண்டறிகிறது…", live: "நேரடி", ready: "தயார்",
    entities: "நிறுவனங்கள்", routes: "வழிகள்",
    calculatingRoutes: "வழிகளைக் கணக்கிடுகிறது…",
    placeDemoOrder: "டெமோ ஆர்டர் வைக்கவும்",
    advanceStatus: "நிலையை முன்னேற்று", stopDemo: "டெமோ நிறுத்து",
    saveImperfectProduce: "அரிய விளைபொருட்களைக் காப்பாற்றுங்கள் 🥕",
    swipeRightToSave: "உணவை சேமிக்க, பணம் சேமிக்க வலதுபுறம் ஸ்வைப் செய்யவும்",
    ofProduceWasted: "விளைபொருட்கள் வீணாகின்றன", priceSavings: "விலை சேமிப்பு",
    equallyNutritious: "சம ஊட்டச்சத்து",
    addProduct: "பொருள் சேர்", searchProducts: "பொருட்களைத் தேடு…",
    productName: "பொருளின் பெயர்", category: "வகை",
    pricePerKg: "விலை (₹/kg)", availableKg: "கிடைக்கும் (kg)",
    freshnessDays: "புத்துணர்ச்சி (நாட்கள்)", organic: "இயற்கை",
    uglyProduceToggle: "சிறப்பு விளைபொருள்", saveChanges: "மாற்றங்களை சேமி",
    noProductsFound: "பொருட்கள் இல்லை", editProduct: "பொருளைத் திருத்து",
    sellerOrders: "விற்பனையாளர் ஆர்டர்கள்",
    trackManageBuyerOrders: "வாங்குபவர் ஆர்டர்களை நிகழ்நேரத்தில் கண்காணிக்கவும்",
    noOrdersYet: "இன்னும் ஆர்டர்கள் இல்லை",
    earningsTitle: "வருமானம்", trackDeliveryIncome: "உங்கள் டெலிவரி வருமானத்தைக் கண்காணிக்கவும்",
    thisWeek: "இந்த வாரம்", totalTrips: "மொத்த பயணங்கள்", totalDistance: "மொத்த தூரம்",
    recentTripHistory: "சமீபத்திய பயண வரலாறு", trips: "பயணங்கள்",
    monteCarloRiskEngine: "மான்டே கார்லோ ரிஸ்க் இயந்திரம் 📊",
    riskEngineDesc: "10,000 வானிலை உருவகப்படுத்துதல்களைப் பயன்படுத்தி AI",
    selectLanguage: "மொழியைத் தேர்ந்தெடுக்கவும்", languageChanged: "மொழி மாற்றப்பட்டது!",
    english: "English", tamil: "தமிழ்", malayalam: "മலയാളം",
    nepali: "नेपाली", telugu: "తెలుగు", kannada: "ಕನ್ನಡ",
    nearbyContacts: "வர்த்தக நெட்வொர்க்", nearbySellers: "அருகிலுள்ள விற்பனையாளர்கள்",
    nearbyBuyers: "அருகிலுள்ள வாங்குபவர்கள்", nearbySellersDesc: "விரைவான வர்த்தகத்திற்கு விற்பனையாளர்களைக் கண்டறியவும்",
    nearbyBuyersDesc: "விரைவான வர்த்தகத்திற்கு வாங்குபவர்களைக் கண்டறியவும்",
    allContacts: "அனைத்தும்", favoritesLabel: "பிடித்தவை", dealHistoryLabel: "வரலாறு",
    myContact: "என் சுயவிவரம்", addMyContact: "என் தொடர்பைச் சேர்", searchContacts: "தொடர்புகளைத் தேடு…",
    noContactsFound: "தொடர்புகள் இல்லை", noFavorites: "பிடித்தவை இல்லை",
    noDealHistory: "ஒப்பந்த வரலாறு இல்லை", noMyContact: "உங்கள் தொடர்பைச் சேர்க்கவும்",
    contactAdded: "தொடர்பு சேர்க்கப்பட்டது!", publicContact: "பொது", privateContact: "தனிப்பட்ட",
    makePublic: "மற்றவர்களுக்குத் தெரியும்", optional: "விருப்பம்", addressLabel: "முகவரி",
    order: "ஆர்டர்", sellerContacts: "விற்பனையாளர் தொடர்புகள்",
    addedToCart: "கூடையில் சேர்க்கப்பட்டது", itemsAddedToCart: "பொருட்கள் கூடையில்",
    trendingHarvest: "டிரெண்டிங் ஹார்வெஸ்ட்", trendingHarvestTitle: "டிரெண்டிங் ஹார்வெஸ்ட் 🌿",
    trendingHarvestDesc: "சிறந்த விலையில் தனித்துவமான விளைபொருட்கள்!",
  },

  ml: {
    back: "പിന്നോട്ട്", close: "അടയ്ക്കുക", confirm: "സ്ഥിരീകരിക്കുക", save: "സേവ് ചെയ്യുക",
    cancel: "റദ്ദാക്കുക", edit: "എഡിറ്റ് ചെയ്യുക", delete: "ഇല്ലാതാക്കുക",
    loading: "ലോഡ് ചെയ്യുന്നു...", error: "പിശക്", success: "വിജയം",
    logout: "ലോഗൗട്ട്", login: "ലോഗിൻ", submit: "സമർപ്പിക്കുക",
    signIn: "സൈൻ ഇൻ", createAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
    welcomeBack: "തിരികെ സ്വാഗതം", joinHarvestLog: "Harvest-Log-ൽ ചേരുക",
    enterCredentials: "നിങ്ങളുടെ അക്കൗണ്ട് ആക്സസ് ചെയ്യാൻ ക്രെഡൻഷ്യലുകൾ നൽകുക",
    createAccountDesc: "ഉൽപ്പന്നങ്ങൾ ട്രേഡ് ചെയ്യാൻ ഒരു അക്കൗണ്ട് സൃഷ്ടിക്കുക",
    fullName: "പൂർണ്ണ നാമം", enterYourName: "നിങ്ങളുടെ പേര് നൽകുക",
    phoneNumber: "ഫോൺ നമ്പർ", email: "ഇമെയിൽ", password: "പാസ്‌വേഡ്",
    enterPassword: "പാസ്‌വേഡ് നൽകുക",
    iWantTo: "എനിക്ക് വേണ്ടത്", buyer: "വാങ്ങുന്നയാൾ", seller: "വിൽപ്പനക്കാരൻ",
    transporter: "ഗതാഗതക്കാരൻ", purchaseProduce: "പുതിയ ഉൽപ്പന്നങ്ങൾ വാങ്ങുക",
    sellYourHarvest: "നിങ്ങളുടെ വിളവ് വിൽക്കുക", deliverAndEarn: "ഡെലിവറി ചെയ്ത് സമ്പാദിക്കുക",
    orTryDemo: "അല്ലെങ്കിൽ ഡെമോ",
    connectingFarms: "കൃഷിയിടങ്ങളെ ബന്ധിപ്പിക്കുന്നു", toMarkets: "വിപണികളിലേക്ക്,",
    intelligently: "ബുദ്ധിപരമായി.",
    platformDesc: "തത്സമയ ലോജിസ്റ്റിക്സ്, AI വിപണി ഇന്റലിജൻസ്, കാർഷിക ക്രെഡിറ്റ് വിലയിരുത്തൽ.",
    realTimeGps: "തത്സമയ GPS", smartRoutes: "സ്മാർട്ട് റൂട്ടുകൾ",
    riskEngine: "റിസ്ക് എഞ്ചിൻ", liveChat: "ലൈവ് ചാറ്റ്",
    agriFintech: "കാർഷിക-FinTech പ്ലാറ്റ്ഫോം",
    startTrading: "ട്രേഡിംഗ് തുടങ്ങുക", watchDemo: "ഡെമോ കാണുക",
    marketplace: "വിപണി", orderAndTrack: "ഓർഡർ & ട്രാക്ക്",
    uglyProduce: "ഓൺ-ഡിമാൻഡ് പിക്സ്", myOrders: "എന്റെ ഓർഡറുകൾ",
    dashboard: "ഡാഷ്ബോർഡ്", inventory: "ഇൻവെന്ററി", orders: "ഓർഡറുകൾ",
    analytics: "അനലിറ്റിക്സ്", activeRide: "ആക്ടീവ് റൈഡ്", earnings: "വരുമാനം",
    welcomeBackDash: "തിരികെ സ്വാഗതം! 👋",
    trackOrdersDiscover: "നിങ്ങളുടെ ഓർഡറുകൾ ട്രാക്ക് ചെയ്ത് പുതിയ ഉൽപ്പന്നങ്ങൾ കണ്ടെത്തുക",
    browseMarket: "വിപണി ബ്രൗസ് ചെയ്യുക", findFreshProduce: "പുതിയ ഉൽപ്പന്നങ്ങൾ കണ്ടെത്തുക",
    liveDeliveryTracking: "ലൈവ് ഡെലിവറി ട്രാക്കിംഗ്",
    saveFood: "ഭക്ഷണം ലാഭിക്കുക", uglyProduceDeals: "പ്രത്യേക ഡീലുകൾ",
    trackDeliveries: "ഡെലിവറികൾ ട്രാക്ക് ചെയ്യുക",
    recentOrders: "സമീപകാല ഓർഡറുകൾ", viewAll: "എല്ലാം കാണുക",
    sellerDashboard: "വിൽപ്പനക്കാരന്റെ ഡാഷ്ബോർഡ് 🌾",
    manageInventoryTrack: "നിങ്ങളുടെ ഇൻവെന്ററി നിയന്ത്രിക്കുക",
    totalProducts: "ആകെ ഉൽപ്പന്നങ്ങൾ", activeOrders: "സജീവ ഓർഡറുകൾ",
    revenueMtd: "വരുമാനം (MTD)", avgRating: "ശരാശരി റേറ്റിംഗ്",
    manageInventory: "ഇൻവെന്ററി നിയന്ത്രിക്കുക", addEditRemove: "ഉൽപ്പന്നങ്ങൾ ചേർക്കുക, എഡിറ്റ് ചെയ്യുക",
    pendingOrders: "കാത്തിരിക്കുന്ന ഓർഡറുകൾ", ordersAwaitingAction: "പ്രവർത്തനം കാത്തിരിക്കുന്ന ഓർഡറുകൾ",
    recentActivity: "സമീപകാല പ്രവർത്തനം",
    transporterDashboard: "ഗതാഗത ഡാഷ്ബോർഡ് 🚚",
    acceptDeliveriesMaximize: "ഡെലിവറികൾ സ്വീകരിച്ച് വരുമാനം വർധിപ്പിക്കുക",
    totalDeliveries: "ആകെ ഡെലിവറികൾ", distanceKm: "ദൂരം (km)",
    earningsMtd: "വരുമാനം (MTD)", nearbyRequests: "സമീപ അഭ്യർത്ഥനകൾ",
    noNearbyRequests: "ഇപ്പോൾ സമീപ അഭ്യർത്ഥനകൾ ഇല്ല",
    estEarnings: "കണക്കാക്കിയ വരുമാനം", reject: "നിരസിക്കുക", accept: "സ്വീകരിക്കുക",
    browseFreshProduce: "പ്രാദേശിക കർഷകരിൽ നിന്ന് പുതിയ ഉൽപ്പന്നങ്ങൾ",
    searchProductsSellers: "ഉൽപ്പന്നങ്ങൾ അല്ലെങ്കിൽ വിൽപ്പനക്കാരെ തിരയുക...",
    all: "എല്ലാം", yourCart: "നിങ്ങളുടെ കാർട്ട്", subtotal: "ഉപമൊത്തം",
    deliveryFee: "ഡെലിവറി ഫീ", total: "ആകെ", proceedToCheckout: "ചെക്കൗട്ടിലേക്ക്",
    items: "ഇനങ്ങൾ",
    orderAndTracking: "ഓർഡർ & ട്രാക്കിംഗ്",
    placeOrdersTrackChat: "ഓർഡറുകൾ നൽകുക, ഡെലിവറികൾ ട്രാക്ക് ചെയ്യുക",
    locating: "കണ്ടെത്തുന്നു…", live: "ലൈവ്", ready: "തയ്യാർ",
    entities: "എന്റിറ്റികൾ", routes: "റൂട്ടുകൾ", calculatingRoutes: "റൂട്ടുകൾ കണക്കാക്കുന്നു…",
    placeDemoOrder: "ഡെമോ ഓർഡർ", advanceStatus: "സ്ഥിതി മുന്നേറ്റം", stopDemo: "ഡെമോ നിർത്തുക",
    saveImperfectProduce: "അപൂർണ ഉൽപ്പന്നങ്ങൾ ലാഭിക്കുക 🥕",
    swipeRightToSave: "ഭക്ഷണം ലാഭിക്കാൻ വലത്തോട്ട് സ്വൈപ്പ് ചെയ്യുക",
    addProduct: "ഉൽപ്പന്നം ചേർക്കുക", searchProducts: "ഉൽപ്പന്നങ്ങൾ തിരയുക…",
    productName: "ഉൽപ്പന്ന നാമം", category: "വിഭാഗം",
    sellerOrders: "വിൽപ്പനക്കാരന്റെ ഓർഡറുകൾ",
    trackManageBuyerOrders: "തത്സമയത്തിൽ വാങ്ങുന്നയാളുടെ ഓർഡറുകൾ ട്രാക്ക് ചെയ്യുക",
    earningsTitle: "വരുമാനം", trackDeliveryIncome: "നിങ്ങളുടെ ഡെലിവറി വരുമാനം ട്രാക്ക് ചെയ്യുക",
    thisWeek: "ഈ ആഴ്ച", totalTrips: "ആകെ ട്രിപ്പുകൾ", totalDistance: "ആകെ ദൂരം",
    recentTripHistory: "സമീപകാല ട്രിപ്പ് ചരിത്രം", trips: "ട്രിപ്പുകൾ",
    monteCarloRiskEngine: "മോണ്ടെ കാർലോ റിസ്ക് എഞ്ചിൻ 📊",
    selectLanguage: "ഭാഷ തിരഞ്ഞെടുക്കുക", languageChanged: "ഭാഷ മാറ്റി!",
    english: "English", tamil: "தமிழ்", malayalam: "മലയാളം",
    nepali: "नेपाली", telugu: "తెలుగు", kannada: "ಕನ್ನಡ",
    nearbyContacts: "ട്രേഡ് നെറ്റ്‌വർക്ക്", nearbySellers: "സമീപത്തെ വിൽപ്പനക്കാർ",
    nearbyBuyers: "സമീപത്തെ വാങ്ങുന്നവർ", nearbySellersDesc: "വേഗത്തിലുള്ള വ്യാപാരത്തിനായി വിൽപ്പനക്കാരെ കണ്ടെത്തുക",
    nearbyBuyersDesc: "വേഗത്തിലുള്ള വ്യാപാരത്തിനായി വാങ്ങുന്നവരെ കണ്ടെത്തുക",
    allContacts: "എല്ലാം", favoritesLabel: "പ്രിയങ്കരങ്ങൾ", dealHistoryLabel: "ചരിത്രം",
    myContact: "എന്റെ പ്രൊഫൈൽ", addMyContact: "എന്റെ കോൺടാക്ട് ചേർക്കുക", searchContacts: "കോൺടാക്ടുകൾ തിരയുക…",
    noContactsFound: "കോൺടാക്ടുകൾ കണ്ടെത്തിയില്ല", noFavorites: "പ്രിയങ്കരങ്ങൾ ഇല്ല",
    noDealHistory: "ഡീൽ ചരിത്രം ഇല്ല", noMyContact: "നിങ്ങളുടെ കോൺടാക്ട് ചേർക്കുക",
    contactAdded: "കോൺടാക്ട് ചേർത്തു!", publicContact: "പൊതു", privateContact: "സ്വകാര്യം",
    makePublic: "മറ്റുള്ളവർക്ക് ദൃശ്യമാക്കുക", optional: "ഐച്ഛികം", addressLabel: "വിലാസം",
    order: "ഓർഡർ", sellerContacts: "വിൽപ്പനക്കാരന്റെ കോൺടാക്ടുകൾ",
    addedToCart: "കാർട്ടിൽ ചേർത്തു", itemsAddedToCart: "ഇനങ്ങൾ കാർട്ടിൽ",
    trendingHarvest: "ട്രെൻഡിംഗ് ഹാർവെസ്റ്റ്", trendingHarvestTitle: "ട്രെൻഡിംഗ് ഹാർവെസ്റ്റ് 🌿",
    trendingHarvestDesc: "മികച്ച വിലയിൽ അതുല്യ ഉൽപ്പന്നങ്ങൾ — കാർട്ടിൽ ചേർക്കാൻ വലത്തേക്ക് സ്വൈപ്പ് ചെയ്യുക!",
  },

  ne: {
    back: "पछाडि", close: "बन्द", confirm: "पुष्टि", save: "बचत", cancel: "रद्द",
    edit: "सम्पादन", delete: "मेटाउनुहोस्", loading: "लोड हुँदैछ...", error: "त्रुटि", success: "सफलता",
    logout: "लगआउट", login: "लगइन", submit: "पेश गर्नुहोस्",
    signIn: "साइन इन", createAccount: "खाता बनाउनुहोस्", welcomeBack: "फेरि स्वागत छ",
    joinHarvestLog: "Harvest-Log मा सामेल हुनुहोस्",
    enterCredentials: "आफ्नो खाता पहुँच गर्न प्रमाणपत्रहरू प्रविष्ट गर्नुहोस्",
    createAccountDesc: "उत्पादन व्यापार सुरु गर्न खाता बनाउनुहोस्",
    fullName: "पूरा नाम", enterYourName: "आफ्नो नाम प्रविष्ट गर्नुहोस्",
    phoneNumber: "फोन नम्बर", email: "इमेल", password: "पासवर्ड",
    enterPassword: "पासवर्ड प्रविष्ट गर्नुहोस्",
    iWantTo: "म चाहन्छु", buyer: "किन्ने", seller: "बेच्ने", transporter: "ढुवानीकर्ता",
    purchaseProduce: "ताजा उत्पादन किन्नुहोस्", sellYourHarvest: "आफ्नो बाली बेच्नुहोस्",
    deliverAndEarn: "डेलिभरी गर्नुहोस् र कमाउनुहोस्", orTryDemo: "वा डेमो",
    connectingFarms: "खेतहरू जोड्दै", toMarkets: "बजारहरूमा,", intelligently: "बुद्धिमान रूपमा.",
    platformDesc: "वास्तविक समय लजिस्टिक्स, AI बजार बुद्धिमत्ता, र कृषि ऋण मूल्यांकन.",
    realTimeGps: "वास्तविक समय GPS", smartRoutes: "स्मार्ट मार्गहरू",
    riskEngine: "जोखिम इन्जिन", liveChat: "लाइभ च्याट", agriFintech: "कृषि-FinTech प्लेटफर्म",
    startTrading: "व्यापार सुरु", watchDemo: "डेमो हेर्नुहोस्",
    marketplace: "बजार", orderAndTrack: "अर्डर र ट्र्याक", uglyProduce: "अन-डिमान्ड पिक्स",
    myOrders: "मेरा अर्डरहरू", dashboard: "ड्यासबोर्ड", inventory: "सूची",
    orders: "अर्डरहरू", analytics: "विश्लेषण", activeRide: "सक्रिय सवारी", earnings: "आम्दानी",
    welcomeBackDash: "फेरि स्वागत छ! 👋",
    trackOrdersDiscover: "आफ्ना अर्डरहरू ट्र्याक गर्नुहोस् र ताजा उत्पादन पत्ता लगाउनुहोस्",
    browseMarket: "बजार ब्राउज", findFreshProduce: "ताजा उत्पादन फेला पार्नुहोस्",
    liveDeliveryTracking: "लाइभ डेलिभरी ट्र्याकिङ",
    saveFood: "खाना बचाउनुहोस्", recentOrders: "हालका अर्डरहरू", viewAll: "सबै हेर्नुहोस्",
    sellerDashboard: "विक्रेता ड्यासबोर्ड 🌾",
    transporterDashboard: "ढुवानी ड्यासबोर्ड 🚚",
    nearbyRequests: "नजिकका अनुरोधहरू", noNearbyRequests: "अहिले नजिकका अनुरोधहरू छैनन्",
    reject: "अस्वीकार", accept: "स्वीकार",
    yourCart: "तपाईंको कार्ट", subtotal: "उपकुल", deliveryFee: "डेलिभरी शुल्क",
    total: "कुल", proceedToCheckout: "चेकआउटमा जानुहोस्", items: "वस्तुहरू",
    orderAndTracking: "अर्डर र ट्र्याकिङ",
    locating: "पत्ता लगाउँदै…", live: "लाइभ", ready: "तयार",
    addProduct: "उत्पादन थप्नुहोस्", sellerOrders: "विक्रेता अर्डरहरू",
    earningsTitle: "आम्दानी", monteCarloRiskEngine: "मोन्टे कार्लो जोखिम इन्जिन 📊",
    selectLanguage: "भाषा चयन गर्नुहोस्", languageChanged: "भाषा परिवर्तन!",
    english: "English", tamil: "தமிழ்", malayalam: "മലയാളം",
    nepali: "नेपाली", telugu: "తెలుగు", kannada: "ಕನ್ನಡ",
    nearbyContacts: "व्यापार नेटवर्क", nearbySellers: "नजिकका विक्रेताहरू",
    nearbyBuyers: "नजिकका किन्नेहरू", nearbySellersDesc: "छिटो व्यापारको लागि विक्रेताहरू फेला पार्नुहोस्",
    nearbyBuyersDesc: "छिटो व्यापारको लागि किन्नेहरू फेला पार्नुहोस्",
    allContacts: "सबै", favoritesLabel: "मनपर्ने", dealHistoryLabel: "इतिहास",
    myContact: "मेरो प्रोफाइल", addMyContact: "मेरो सम्पर्क थप्नुहोस्", searchContacts: "सम्पर्कहरू खोज्नुहोस्…",
    noContactsFound: "सम्पर्कहरू भेटिएनन्", noFavorites: "मनपर्ने छैन",
    noDealHistory: "सम्झौता इतिहास छैन", noMyContact: "आफ्नो सम्पर्क थप्नुहोस्",
    contactAdded: "सम्पर्क थपियो!", publicContact: "सार्वजनिक", privateContact: "निजी",
    makePublic: "अरूलाई देखाउनुहोस्", optional: "वैकल्पिक", addressLabel: "ठेगाना",
    order: "अर्डर", sellerContacts: "विक्रेता सम्पर्कहरू",
    addedToCart: "कार्टमा थपियो", itemsAddedToCart: "वस्तुहरू कार्टमा",
    trendingHarvest: "ट्रेन्डिङ हार्वेस्ट", trendingHarvestTitle: "ट्रेन्डिङ हार्वेस्ट 🌿",
    trendingHarvestDesc: "उत्कृष्ट मूल्यमा अद्वितीय उत्पादनहरू — कार्टमा थप्न दायाँ स्वाइप गर्नुहोस्!",
  },

  te: {
    back: "వెనక్కి", close: "మూసివేయి", confirm: "నిర్ధారించు", save: "సేవ్", cancel: "రద్దు",
    edit: "సవరించు", delete: "తొలగించు", loading: "లోడ్ అవుతోంది...", error: "ఎర్రర్", success: "విజయం",
    logout: "లాగ్అవుట్", login: "లాగిన్", submit: "సమర్పించు",
    signIn: "సైన్ ఇన్", createAccount: "ఖాతా సృష్టించు", welcomeBack: "తిరిగి స్వాగతం",
    joinHarvestLog: "Harvest-Log లో చేరండి",
    enterCredentials: "మీ ఖాతాను యాక్సెస్ చేయడానికి ఆధారాలను నమోదు చేయండి",
    createAccountDesc: "ఉత్పత్తులను ట్రేడ్ చేయడానికి ఖాతాను సృష్టించండి",
    fullName: "పూర్తి పేరు", enterYourName: "మీ పేరు నమోదు చేయండి",
    phoneNumber: "ఫోన్ నంబర్", email: "ఇమెయిల్", password: "పాస్‌వర్డ్",
    enterPassword: "పాస్‌వర్డ్ నమోదు చేయండి",
    iWantTo: "నాకు కావలసింది", buyer: "కొనుగోలుదారు", seller: "విక్రేత",
    transporter: "రవాణాదారు", purchaseProduce: "తాజా ఉత్పత్తులను కొనుగోలు చేయండి",
    sellYourHarvest: "మీ పంటను అమ్మండి", deliverAndEarn: "డెలివరీ చేసి సంపాదించండి",
    orTryDemo: "లేదా డెమో",
    connectingFarms: "పొలాలను కలుపుతోంది", toMarkets: "మార్కెట్లకు,", intelligently: "తెలివిగా.",
    platformDesc: "రియల్-టైమ్ లాజిస్టిక్స్, AI మార్కెట్ ఇంటెలిజెన్స్, వ్యవసాయ క్రెడిట్ అంచనా.",
    realTimeGps: "రియల్-టైమ్ GPS", smartRoutes: "స్మార్ట్ రూట్లు",
    riskEngine: "రిస్క్ ఇంజిన్", liveChat: "లైవ్ చాట్", agriFintech: "వ్యవసాయ-FinTech ప్లాట్‌ఫారమ్",
    startTrading: "ట్రేడింగ్ ప్రారంభించు", watchDemo: "డెమో చూడు",
    marketplace: "మార్కెట్‌ప్లేస్", orderAndTrack: "ఆర్డర్ & ట్రాక్",
    uglyProduce: "ఆన్-డిమాండ్ పిక్స్", myOrders: "నా ఆర్డర్లు",
    dashboard: "డ్యాష్‌బోర్డ్", inventory: "ఇన్వెంటరీ", orders: "ఆర్డర్లు",
    analytics: "అనలిటిక్స్", activeRide: "యాక్టివ్ రైడ్", earnings: "ఆదాయం",
    welcomeBackDash: "తిరిగి స్వాగతం! 👋",
    trackOrdersDiscover: "మీ ఆర్డర్లను ట్రాక్ చేసి తాజా ఉత్పత్తులను కనుగొనండి",
    browseMarket: "మార్కెట్ బ్రౌజ్", findFreshProduce: "తాజా ఉత్పత్తులను కనుగొనండి",
    liveDeliveryTracking: "లైవ్ డెలివరీ ట్రాకింగ్",
    saveFood: "ఆహారం ఆదా చేయండి", recentOrders: "ఇటీవలి ఆర్డర్లు", viewAll: "అన్నీ చూడు",
    sellerDashboard: "విక్రేత డ్యాష్‌బోర్డ్ 🌾",
    transporterDashboard: "రవాణా డ్యాష్‌బోర్డ్ 🚚",
    nearbyRequests: "సమీపంలోని అభ్యర్థనలు", noNearbyRequests: "ప్రస్తుతం సమీపంలో అభ్యర్థనలు లేవు",
    reject: "తిరస్కరించు", accept: "అంగీకరించు",
    yourCart: "మీ కార్ట్", subtotal: "ఉపమొత్తం", deliveryFee: "డెలివరీ ఫీ",
    total: "మొత్తం", proceedToCheckout: "చెక్అవుట్‌కు వెళ్ళండి", items: "అంశాలు",
    orderAndTracking: "ఆర్డర్ & ట్రాకింగ్",
    locating: "గుర్తిస్తోంది…", live: "లైవ్", ready: "సిద్ధం",
    addProduct: "ఉత్పత్తి జోడించు", sellerOrders: "విక్రేత ఆర్డర్లు",
    earningsTitle: "ఆదాయం", monteCarloRiskEngine: "మోంటే కార్లో రిస్క్ ఇంజిన్ 📊",
    selectLanguage: "భాషను ఎంచుకోండి", languageChanged: "భాష మార్చబడింది!",
    english: "English", tamil: "தமிழ்", malayalam: "മലയാളം",
    nepali: "नेपाली", telugu: "తెలుగు", kannada: "ಕನ್ನಡ",
  },

  kn: {
    back: "ಹಿಂದೆ", close: "ಮುಚ್ಚಿ", confirm: "ದೃಢೀಕರಿಸಿ", save: "ಉಳಿಸಿ", cancel: "ರದ್ದು",
    edit: "ಸಂಪಾದಿಸಿ", delete: "ಅಳಿಸಿ", loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...", error: "ದೋಷ", success: "ಯಶಸ್ಸು",
    logout: "ಲಾಗ್ಔಟ್", login: "ಲಾಗಿನ್", submit: "ಸಲ್ಲಿಸಿ",
    signIn: "ಸೈನ್ ಇನ್", createAccount: "ಖಾತೆ ರಚಿಸಿ", welcomeBack: "ಮರಳಿ ಸ್ವಾಗತ",
    joinHarvestLog: "Harvest-Log ಗೆ ಸೇರಿ",
    enterCredentials: "ನಿಮ್ಮ ಖಾತೆಯನ್ನು ಪ್ರವೇಶಿಸಲು ರುಜುವಾತುಗಳನ್ನು ನಮೂದಿಸಿ",
    createAccountDesc: "ಉತ್ಪನ್ನಗಳನ್ನು ವ್ಯಾಪಾರ ಮಾಡಲು ಖಾತೆ ರಚಿಸಿ",
    fullName: "ಪೂರ್ಣ ಹೆಸರು", enterYourName: "ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
    phoneNumber: "ಫೋನ್ ಸಂಖ್ಯೆ", email: "ಇಮೇಲ್", password: "ಪಾಸ್‌ವರ್ಡ್",
    enterPassword: "ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ",
    iWantTo: "ನನಗೆ ಬೇಕಾದ", buyer: "ಖರೀದಿದಾರ", seller: "ಮಾರಾಟಗಾರ",
    transporter: "ಸಾಗಣೆದಾರ", purchaseProduce: "ತಾಜಾ ಉತ್ಪನ್ನಗಳನ್ನು ಖರೀದಿಸಿ",
    sellYourHarvest: "ನಿಮ್ಮ ಬೆಳೆ ಮಾರಾಟ ಮಾಡಿ", deliverAndEarn: "ಡೆಲಿವರಿ ಮಾಡಿ ಗಳಿಸಿ",
    orTryDemo: "ಅಥವಾ ಡೆಮೊ",
    connectingFarms: "ಕೃಷಿಕ್ಷೇತ್ರಗಳನ್ನು ಸಂಪರ್ಕಿಸುತ್ತಿದೆ", toMarkets: "ಮಾರುಕಟ್ಟೆಗಳಿಗೆ,",
    intelligently: "ಬುದ್ಧಿವಂತವಾಗಿ.",
    platformDesc: "ನೈಜ-ಸಮಯ ಲಾಜಿಸ್ಟಿಕ್ಸ್, AI ಮಾರುಕಟ್ಟೆ ಬುದ್ಧಿಮತ್ತೆ, ಮತ್ತು ಕೃಷಿ ಕ್ರೆಡಿಟ್ ಮೌಲ್ಯಮಾಪನ.",
    realTimeGps: "ನೈಜ-ಸಮಯ GPS", smartRoutes: "ಸ್ಮಾರ್ಟ್ ಮಾರ್ಗಗಳು",
    riskEngine: "ರಿಸ್ಕ್ ಎಂಜಿನ್", liveChat: "ಲೈವ್ ಚಾಟ್", agriFintech: "ಕೃಷಿ-FinTech ಪ್ಲಾಟ್‌ಫಾರ್ಮ್",
    startTrading: "ವ್ಯಾಪಾರ ಪ್ರಾರಂಭಿಸಿ", watchDemo: "ಡೆಮೊ ನೋಡಿ",
    marketplace: "ಮಾರುಕಟ್ಟೆ", orderAndTrack: "ಆರ್ಡರ್ & ಟ್ರ್ಯಾಕ್",
    uglyProduce: "ಆನ್-ಡಿಮಾಂಡ್ ಪಿಕ್ಸ್", myOrders: "ನನ್ನ ಆರ್ಡರ್‌ಗಳು",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", inventory: "ಇನ್ವೆಂಟರಿ", orders: "ಆರ್ಡರ್‌ಗಳು",
    analytics: "ಅನಲಿಟಿಕ್ಸ್", activeRide: "ಆಕ್ಟಿವ್ ರೈಡ್", earnings: "ಗಳಿಕೆ",
    welcomeBackDash: "ಮರಳಿ ಸ್ವಾಗತ! 👋",
    trackOrdersDiscover: "ನಿಮ್ಮ ಆರ್ಡರ್‌ಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ತಾಜಾ ಉತ್ಪನ್ನಗಳನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ",
    browseMarket: "ಮಾರುಕಟ್ಟೆ ಬ್ರೌಸ್", findFreshProduce: "ತಾಜಾ ಉತ್ಪನ್ನಗಳನ್ನು ಹುಡುಕಿ",
    liveDeliveryTracking: "ಲೈವ್ ಡೆಲಿವರಿ ಟ್ರ್ಯಾಕಿಂಗ್",
    saveFood: "ಆಹಾರ ಉಳಿಸಿ", recentOrders: "ಇತ್ತೀಚಿನ ಆರ್ಡರ್‌ಗಳು", viewAll: "ಎಲ್ಲಾ ವೀಕ್ಷಿಸಿ",
    sellerDashboard: "ಮಾರಾಟಗಾರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ 🌾",
    transporterDashboard: "ಸಾಗಣೆ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ 🚚",
    nearbyRequests: "ಹತ್ತಿರದ ವಿನಂತಿಗಳು", noNearbyRequests: "ಪ್ರಸ್ತುತ ಹತ್ತಿರದ ವಿನಂತಿಗಳಿಲ್ಲ",
    reject: "ತಿರಸ್ಕರಿಸಿ", accept: "ಸ್ವೀಕರಿಸಿ",
    yourCart: "ನಿಮ್ಮ ಕಾರ್ಟ್", subtotal: "ಉಪಮೊತ್ತ", deliveryFee: "ಡೆಲಿವರಿ ಶುಲ್ಕ",
    total: "ಒಟ್ಟು", proceedToCheckout: "ಚೆಕ್‌ಔಟ್‌ಗೆ ಮುಂದುವರಿಯಿರಿ", items: "ಐಟಂಗಳು",
    orderAndTracking: "ಆರ್ಡರ್ & ಟ್ರ್ಯಾಕಿಂಗ್",
    locating: "ಹುಡುಕುತ್ತಿದೆ…", live: "ಲೈವ್", ready: "ಸಿದ್ಧ",
    addProduct: "ಉತ್ಪನ್ನ ಸೇರಿಸಿ", sellerOrders: "ಮಾರಾಟಗಾರ ಆರ್ಡರ್‌ಗಳು",
    earningsTitle: "ಗಳಿಕೆ", monteCarloRiskEngine: "ಮಾಂಟೆ ಕಾರ್ಲೊ ರಿಸ್ಕ್ ಎಂಜಿನ್ 📊",
    selectLanguage: "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ", languageChanged: "ಭಾಷೆ ಬದಲಾಯಿಸಲಾಗಿದೆ!",
    english: "English", tamil: "தமிழ்", malayalam: "മലയാളം",
    nepali: "नेपाली", telugu: "తెలుగు", kannada: "ಕನ್ನಡ",
    nearbyContacts: "ವ್ಯಾಪಾರ ನೆಟ್‌ವರ್ಕ್", nearbySellers: "ಹತ್ತಿರದ ಮಾರಾಟಗಾರರು",
    nearbyBuyers: "ಹತ್ತಿರದ ಖರೀದಿದಾರರು", nearbySellersDesc: "ತ್ವರಿತ ವ್ಯಾಪಾಕ್ಕಾಗಿ ಮಾರಾಟಗಾರರನ್ನು ಹುಡುಕಿ",
    nearbyBuyersDesc: "ತ್ವರಿತ ವ್ಯಾಪಾಕ್ಕಾಗಿ ಖರೀದಿದಾರರನ್ನು ಹುಡುಕಿ",
    allContacts: "ಎಲ್ಲಾ", favoritesLabel: "ಮೆಚ್ಚಿನವು", dealHistoryLabel: "ಇತಿಹಾಸ",
    myContact: "ನನ್ನ ಪ್ರೊಫೈಲ್", addMyContact: "ನನ್ನ ಕಾಂಟ್ಯಾಕ್ಟ್ ಸೇರಿಸಿ",
    searchContacts: "ಕಾಂಟ್ಯಾಕ್ಟ್‌ಗಳನ್ನು ಹುಡುಕಿ…",
    noContactsFound: "ಕಾಂಟ್ಯಾಕ್ಟ್‌ಗಳು ಕಂಡುಬಂದಿಲ್ಲ", noFavorites: "ಮೆಚ್ಚಿನವು ಇಲ್ಲ",
    noDealHistory: "ಡೀಲ್ ಇತಿಹಾಸ ಇಲ್ಲ", noMyContact: "ನಿಮ್ಮ ಕಾಂಟ್ಯಾಕ್ಟ್ ಸೇರಿಸಿ",
    contactAdded: "ಕಾಂಟ್ಯಾಕ್ಟ್ ಸೇರಿಸಲಾಗಿದೆ!", publicContact: "ಸಾರ್ವಜನಿಕ", privateContact: "ಖಾಸಗಿ",
    makePublic: "ಇತರಿಗೆ ಕಾಣುವಂತೆ ಮಾಡಿ", optional: "ಐಚ್ಛಿಕ", addressLabel: "ವಿಳಾಸ",
    order: "ಆರ್ಡರ್", sellerContacts: "ಮಾರಾಟಗಾರ ಕಾಂಟ್ಯಾಕ್ಟ್‌ಗಳು",
    addedToCart: "ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಲಾಗಿದೆ", itemsAddedToCart: "ಐಟಂಗಳು ಕಾರ್ಟ್‌ನಲ್ಲಿ",
    trendingHarvest: "ಟ್ರೆಂಡಿಂಗ್ ಹಾರ್ವೆಸ್ಟ್", trendingHarvestTitle: "ಟ್ರೆಂಡಿಂಗ್ ಹಾರ್ವೆಸ್ಟ್ 🌿",
    trendingHarvestDesc: "ಅತ್ಯುತ್ತಮ ಬೆಲೆಯಲ್ಲಿ ವಿಶಿಷ್ಟ ಉತ್ಪನ್ನಗಳು!",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('harvest-log-language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('harvest-log-language', lang);
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
